#include "items.hpp"

#include <array>
#include <format>

const ItemInfo& get_item_info(ItemId id) {
  static const std::array item_info{std::to_array<ItemInfo>({
      {ItemId::None, "Empty", ItemCategory::Scrap, 0, 0, 0, {0, 0, 0, 0}},
      // Scrap & Tech Nodes
      {ItemId::CopperWireScrap,
       "Copper Wire Scrap",
       ItemCategory::Scrap,
       2,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::PlasteelShards,
       "Plasteel Shards",
       ItemCategory::Scrap,
       5,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::CarbonNanotubes,
       "Carbon Nanotubes",
       ItemCategory::Scrap,
       10,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::OpticFiberBundle,
       "Optic Fiber Bundle",
       ItemCategory::Scrap,
       18,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::PositronicRelays,
       "Positronic Relays",
       ItemCategory::Scrap,
       30,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::CryoCellCore,
       "Cryo-Cell Core",
       ItemCategory::Scrap,
       45,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::PlasmaConduit,
       "Plasma Conduit",
       ItemCategory::Scrap,
       70,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::QuantumNode,
       "Quantum Node",
       ItemCategory::Scrap,
       120,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::AiMainframeCore,
       "AI Mainframe Core",
       ItemCategory::Scrap,
       200,
       0,
       1,
       {0, 0, 0, 0}},

      // Recycled Basic / Raw Materials
      {ItemId::CopperFilament,
       "Copper Filament",
       ItemCategory::RawMaterial,
       6,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::PlasteelPolymer,
       "Plasteel Polymer",
       ItemCategory::RawMaterial,
       14,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::CarbonFiberWeave,
       "Carbon Fiber Weave",
       ItemCategory::RawMaterial,
       28,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::OpticSilicaGlass,
       "Optic Silica Glass",
       ItemCategory::RawMaterial,
       48,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::PositronicWafer,
       "Positronic Wafer",
       ItemCategory::RawMaterial,
       80,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::CryoCoolantGel,
       "Cryo-Coolant Gel",
       ItemCategory::RawMaterial,
       120,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::PlasmaCoil,
       "Magnetic Plasma Coil",
       ItemCategory::RawMaterial,
       185,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::QuantumLattice,
       "Quantum Lattice",
       ItemCategory::RawMaterial,
       310,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::NeuralMatrix,
       "Neural Matrix",
       ItemCategory::RawMaterial,
       520,
       0,
       1,
       {0, 0, 0, 0}},

      // Raw Synth-Biota
      {ItemId::RawKrillBiomass,
       "Raw Krill Biomass",
       ItemCategory::RawBiota,
       3,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawNeonEel,
       "Raw Neon Eel",
       ItemCategory::RawBiota,
       6,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawSynthCarp,
       "Raw Synth-Carp",
       ItemCategory::RawBiota,
       14,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawChromeSalmon,
       "Raw Chrome Salmon",
       ItemCategory::RawBiota,
       24,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawCyberLobster,
       "Raw Cyber-Lobster",
       ItemCategory::RawBiota,
       45,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawPlasmaRay,
       "Raw Plasma Ray",
       ItemCategory::RawBiota,
       75,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawApexShark,
       "Raw Apex Shark",
       ItemCategory::RawBiota,
       140,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawLeviathanCell,
       "Raw Leviathan Cell",
       ItemCategory::RawBiota,
       260,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RawCyberKraken,
       "Raw Cyber-Kraken",
       ItemCategory::RawBiota,
       450,
       0,
       1,
       {0, 0, 0, 0}},

      // Hydro-Farmed Crops & Synth-Noodles
      {ItemId::HydroWheat, "Hydro-Wheat", ItemCategory::Crop, 4, 0, 1, {0, 0, 0, 0}},
      {ItemId::SoyPods, "Synth-Soy Pods", ItemCategory::Crop, 10, 0, 1, {0, 0, 0, 0}},
      {ItemId::NeonScallion,
       "Neon Scallion",
       ItemCategory::Crop,
       22,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::GlowNori,
       "Bioluminescent Nori",
       ItemCategory::Crop,
       42,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::BioBamboo,
       "Cyber-Bamboo Shoot",
       ItemCategory::Crop,
       75,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::CyberShiitake,
       "Spore-Tech Shiitake",
       ItemCategory::Crop,
       130,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::PlasmaChili,
       "Plasma Ghost-Chili",
       ItemCategory::Crop,
       225,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::ChronoLotus,
       "Chrono-Lotus Root",
       ItemCategory::Crop,
       380,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::QuantumTruffle,
       "Quantum Myco-Truffle",
       ItemCategory::Crop,
       650,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::SynthNoodles,
       "Synth-Noodles",
       ItemCategory::Crop,
       8,
       0,
       1,
       {0, 0, 0, 0}},

      // Synthesized Stims, Cyber-Ramen & Toxic Slag
      {ItemId::KrillRation,
       "Krill Ration",
       ItemCategory::StimFood,
       8,
       30,
       1,
       {0, 0, 0, 0}},
      {ItemId::NeonEelSkewer,
       "Neon Eel Skewer",
       ItemCategory::StimFood,
       15,
       50,
       1,
       {0, 0, 0, 0}},
      {ItemId::SynthCarpPack,
       "Synth-Carp Pack",
       ItemCategory::StimFood,
       32,
       80,
       1,
       {0, 0, 0, 0}},
      {ItemId::ChromeSalmonStim,
       "Chrome Salmon Stim",
       ItemCategory::StimFood,
       55,
       110,
       1,
       {0, 0, 0, 0}},
      {ItemId::CyberLobsterMeal,
       "Cyber-Lobster Meal",
       ItemCategory::StimFood,
       100,
       160,
       1,
       {0, 0, 0, 0}},
      {ItemId::PlasmaRayInfusion,
       "Plasma Ray Infusion",
       ItemCategory::StimFood,
       165,
       220,
       1,
       {0, 0, 0, 0}},
      {ItemId::ApexSharkBooster,
       "Apex Shark Booster",
       ItemCategory::StimFood,
       300,
       320,
       1,
       {0, 0, 0, 0}},
      {ItemId::LeviathanNanomed,
       "Leviathan Nanomed",
       ItemCategory::StimFood,
       550,
       480,
       1,
       {0, 0, 0, 0}},
      {ItemId::KrakenBioElixir,
       "Kraken Bio-Elixir",
       ItemCategory::StimFood,
       950,
       680,
       1,
       {0, 0, 0, 0}},
      {ItemId::ShoyuRamen,
       "Soy-Shoyu Cyber-Ramen",
       ItemCategory::StimFood,
       35,
       65,
       1,
       {0, 0, 0, 0}},
      {ItemId::ScallionRamen,
       "Neon Scallion Ramen",
       ItemCategory::StimFood,
       68,
       125,
       1,
       {0, 0, 0, 0}},
      {ItemId::NoriRamen,
       "Glow-Nori Umami Ramen",
       ItemCategory::StimFood,
       135,
       195,
       1,
       {0, 0, 0, 0}},
      {ItemId::BambooRamen,
       "Cyber-Bamboo Miso Ramen",
       ItemCategory::StimFood,
       230,
       280,
       1,
       {0, 0, 0, 0}},
      {ItemId::ShiitakeRamen,
       "Spore-Shiitake Tonkotsu Ramen",
       ItemCategory::StimFood,
       390,
       390,
       1,
       {0, 0, 0, 0}},
      {ItemId::PlasmaChiliRamen,
       "Plasma Volcano Ramen",
       ItemCategory::StimFood,
       680,
       540,
       1,
       {0, 0, 0, 0}},
      {ItemId::ChronoLotusRamen,
       "Chrono-Lotus Broth Ramen",
       ItemCategory::StimFood,
       1150,
       720,
       1,
       {0, 0, 0, 0}},
      {ItemId::TruffleRamen,
       "Quantum Truffle Ramen",
       ItemCategory::StimFood,
       1850,
       860,
       1,
       {0, 0, 0, 0}},
      {ItemId::QuantumKrakenRamen,
       "Quantum Kraken Special Ramen",
       ItemCategory::StimFood,
       2200,
       980,
       1,
       {0, 0, 0, 0}},
      {ItemId::SynthProteinBar,
       "Synth-Protein Bar",
       ItemCategory::StimFood,
       6,
       25,
       1,
       {0, 0, 0, 0}},
      {ItemId::ToxicSlag,
       "Toxic Bio-Slag",
       ItemCategory::ToxicWaste,
       1,
       0,
       1,
       {0, 0, 0, 0}},

      // Deep-Mined Ores & Cells
      {ItemId::CopperOre, "Copper Ore", ItemCategory::RawOre, 4, 0, 1, {0, 0, 0, 0}},
      {ItemId::SiliconOre, "Silicon Ore", ItemCategory::RawOre, 4, 0, 1, {0, 0, 0, 0}},
      {ItemId::TitaniumOre,
       "Titanium Ore",
       ItemCategory::RawOre,
       12,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::CarbonCell, "Carbon Cell", ItemCategory::RawOre, 18, 0, 1, {0, 0, 0, 0}},
      {ItemId::SilverOre, "Silver Ore", ItemCategory::RawOre, 30, 0, 1, {0, 0, 0, 0}},
      {ItemId::GoldOre, "Gold Ore", ItemCategory::RawOre, 50, 0, 1, {0, 0, 0, 0}},
      {ItemId::CobaltOre, "Cobalt Ore", ItemCategory::RawOre, 70, 0, 1, {0, 0, 0, 0}},
      {ItemId::TungstenOre,
       "Tungsten Ore",
       ItemCategory::RawOre,
       120,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::NeutroniumOre,
       "Neutronium Ore",
       ItemCategory::RawOre,
       220,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::ChronoOre,
       "Chrono-Crystal Ore",
       ItemCategory::RawOre,
       400,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::QuantumOre,
       "Quantum Singularity Ore",
       ItemCategory::RawOre,
       750,
       0,
       1,
       {0, 0, 0, 0}},

      // Refined Alloys & Conductors
      {ItemId::ScrapAlloy,
       "Scrap-Alloy Ingot",
       ItemCategory::Alloy,
       15,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::TitaniumAlloy,
       "Titanium Ingot",
       ItemCategory::Alloy,
       32,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::DurasteelAlloy,
       "Durasteel Ingot",
       ItemCategory::Alloy,
       65,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::SilverConductor,
       "Silver Conductor",
       ItemCategory::Alloy,
       80,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::GoldSuperconductor,
       "Gold Superconductor",
       ItemCategory::Alloy,
       130,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::CobaltAlloy,
       "Cobalt-Chrome Ingot",
       ItemCategory::Alloy,
       175,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::TungstenAlloy,
       "Tungsten Ingot",
       ItemCategory::Alloy,
       310,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::NeutroniumAlloy,
       "Neutronium Ingot",
       ItemCategory::Alloy,
       580,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::ChronoAlloy,
       "Chrono-Alloy Ingot",
       ItemCategory::Alloy,
       1100,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::QuantumAlloy,
       "Quantum-Flux Ingot",
       ItemCategory::Alloy,
       2000,
       0,
       1,
       {0, 0, 0, 0}},

      // Data Crystals
      {ItemId::AmberDatachip,
       "Amber Datachip",
       ItemCategory::DataCrystal,
       150,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::SapphireCortex,
       "Sapphire Cortex",
       ItemCategory::DataCrystal,
       250,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::RubyLaserCore,
       "Ruby Laser Core",
       ItemCategory::DataCrystal,
       450,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::EmeraldCryptokey,
       "Emerald Cryptokey",
       ItemCategory::DataCrystal,
       750,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::QuantumDiamond,
       "Quantum Diamond",
       ItemCategory::DataCrystal,
       1500,
       0,
       1,
       {0, 0, 0, 0}},

      // Gears
      // Weapons - Melee
      {ItemId::ScrapBlade,
       "Scrap Vibro-Knife",
       ItemCategory::Weapon,
       45,
       0,
       1,
       {10, 12, 0, 0}},
      {ItemId::TitaniumBlade,
       "Titanium Mono-Blade",
       ItemCategory::Weapon,
       100,
       0,
       5,
       {18, 20, 0, 0}},
      {ItemId::DurasteelBlade,
       "Durasteel Katana",
       ItemCategory::Weapon,
       220,
       0,
       10,
       {28, 32, 0, 0}},
      {ItemId::CobaltBlade,
       "Cobalt Laser-Edge",
       ItemCategory::Weapon,
       550,
       0,
       20,
       {42, 48, 0, 0}},
      {ItemId::TungstenBlade,
       "Tungsten Mantis-Blade",
       ItemCategory::Weapon,
       1100,
       0,
       30,
       {60, 66, 0, 0}},
      {ItemId::NeutroniumBlade,
       "Neutronium Phase-Saber",
       ItemCategory::Weapon,
       2400,
       0,
       40,
       {84, 92, 0, 0}},
      {ItemId::ChronoBlade,
       "Chrono-Edge Katana",
       ItemCategory::Weapon,
       6000,
       0,
       60,
       {120, 130, 0, 0}},
      {ItemId::QuantumBlade,
       "Quantum Singularity Blade",
       ItemCategory::Weapon,
       12000,
       0,
       75,
       {165, 180, 0, 0}},

      // Visors
      {ItemId::ScrapVisor,
       "Scrap Optic Visor",
       ItemCategory::Head,
       40,
       0,
       1,
       {0, 0, 6, 1}},
      {ItemId::TitaniumVisor,
       "Titanium HUD Visor",
       ItemCategory::Head,
       90,
       0,
       5,
       {0, 0, 11, 2}},
      {ItemId::DurasteelVisor,
       "Durasteel Tac-Helm",
       ItemCategory::Head,
       200,
       0,
       10,
       {0, 0, 18, 3}},
      {ItemId::CobaltVisor,
       "Cobalt Neural Visor",
       ItemCategory::Head,
       500,
       0,
       20,
       {0, 0, 27, 4}},
      {ItemId::TungstenVisor,
       "Tungsten Cyber-Helm",
       ItemCategory::Head,
       950,
       0,
       30,
       {0, 0, 38, 5}},
      {ItemId::NeutroniumVisor,
       "Neutronium Mind-Crown",
       ItemCategory::Head,
       2100,
       0,
       40,
       {0, 0, 52, 7}},
      {ItemId::ChronoVisor,
       "Chrono-Sync Visor",
       ItemCategory::Head,
       5200,
       0,
       60,
       {0, 0, 72, 10}},
      {ItemId::QuantumVisor,
       "Quantum Tachyon Visor",
       ItemCategory::Head,
       10500,
       0,
       75,
       {0, 0, 98, 13}},

      // Exo-Suits
      {ItemId::ScrapExoSuit,
       "Scrap Exo-Harness",
       ItemCategory::Armor,
       85,
       0,
       1,
       {0, 0, 14, 2}},
      {ItemId::TitaniumExoSuit,
       "Titanium Flak-Jacket",
       ItemCategory::Armor,
       180,
       0,
       5,
       {0, 0, 24, 3}},
      {ItemId::DurasteelExoSuit,
       "Durasteel Exo-Rig",
       ItemCategory::Armor,
       400,
       0,
       10,
       {0, 0, 36, 5}},
      {ItemId::CobaltExoSuit,
       "Cobalt Subdermal Rig",
       ItemCategory::Armor,
       950,
       0,
       20,
       {0, 0, 52, 7}},
      {ItemId::TungstenExoSuit,
       "Tungsten Power-Armor",
       ItemCategory::Armor,
       1900,
       0,
       30,
       {0, 0, 74, 9}},
      {ItemId::NeutroniumExoSuit,
       "Neutronium Nano-Suit",
       ItemCategory::Armor,
       4200,
       0,
       40,
       {0, 0, 102, 12}},
      {ItemId::ChronoExoSuit,
       "Chrono-Weave Exo-Suit",
       ItemCategory::Armor,
       9800,
       0,
       60,
       {0, 0, 140, 16}},
      {ItemId::QuantumExoSuit,
       "Quantum Phase Exo-Suit",
       ItemCategory::Armor,
       19500,
       0,
       75,
       {0, 0, 190, 20}},

      // Holo-Shields
      {ItemId::ScrapShield,
       "Scrap Riot Buckler",
       ItemCategory::Shield,
       55,
       0,
       1,
       {0, 0, 9, 1}},
      {ItemId::TitaniumShield,
       "Titanium Deflector",
       ItemCategory::Shield,
       120,
       0,
       5,
       {0, 0, 16, 2}},
      {ItemId::DurasteelShield,
       "Durasteel Barrier",
       ItemCategory::Shield,
       260,
       0,
       10,
       {0, 0, 25, 3}},
      {ItemId::CobaltShield,
       "Cobalt Holo-Aegis",
       ItemCategory::Shield,
       620,
       0,
       20,
       {0, 0, 36, 5}},
      {ItemId::TungstenShield,
       "Tungsten Pulse-Shield",
       ItemCategory::Shield,
       1250,
       0,
       30,
       {0, 0, 50, 6}},
      {ItemId::NeutroniumShield,
       "Neutronium Forcefield",
       ItemCategory::Shield,
       2800,
       0,
       40,
       {0, 0, 68, 8}},
      {ItemId::ChronoShield,
       "Chrono-Phase Barrier",
       ItemCategory::Shield,
       6800,
       0,
       60,
       {0, 0, 96, 12}},
      {ItemId::QuantumShield,
       "Quantum Event-Horizon Shield",
       ItemCategory::Shield,
       13500,
       0,
       75,
       {0, 0, 132, 15}},

      // Tools - Salvaging Cutters
      {ItemId::ScrapCutter,
       "Scrap Cutter",
       ItemCategory::Cutter,
       10,
       0,
       1,
       {0, 0, 0, 0, 0}},
      {ItemId::TitaniumCutter,
       "Titanium Cutter",
       ItemCategory::Cutter,
       50,
       0,
       10,
       {0, 0, 0, 0, 6}},
      {ItemId::DurasteelCutter,
       "Durasteel Cutter",
       ItemCategory::Cutter,
       180,
       0,
       25,
       {0, 0, 0, 0, 12}},
      {ItemId::CobaltCutter,
       "Cobalt Laser-Cutter",
       ItemCategory::Cutter,
       625,
       0,
       40,
       {0, 0, 0, 0, 18}},
      {ItemId::TungstenCutter,
       "Tungsten Plasma-Torch",
       ItemCategory::Cutter,
       2000,
       0,
       55,
       {0, 0, 0, 0, 24}},
      {ItemId::NeutroniumCutter,
       "Neutronium Arc-Splicer",
       ItemCategory::Cutter,
       6250,
       0,
       70,
       {0, 0, 0, 0, 30}},
      {ItemId::ChronoCutter,
       "Chrono Deconstructor",
       ItemCategory::Cutter,
       20000,
       0,
       85,
       {0, 0, 0, 0, 38}},

      // Tools - Bio-Harvesters
      {ItemId::ScrapHarvester,
       "Scrap Bio-Net",
       ItemCategory::Harvester,
       10,
       0,
       1,
       {0, 0, 0, 0, 0}},
      {ItemId::TitaniumHarvester,
       "Titanium Bio-Rig",
       ItemCategory::Harvester,
       50,
       0,
       10,
       {0, 0, 0, 0, 6}},
      {ItemId::DurasteelHarvester,
       "Durasteel Bio-Sampler",
       ItemCategory::Harvester,
       180,
       0,
       25,
       {0, 0, 0, 0, 12}},
      {ItemId::CobaltHarvester,
       "Cobalt Gene-Extractor",
       ItemCategory::Harvester,
       625,
       0,
       40,
       {0, 0, 0, 0, 18}},
      {ItemId::TungstenHarvester,
       "Tungsten Drone-Trawler",
       ItemCategory::Harvester,
       2000,
       0,
       55,
       {0, 0, 0, 0, 24}},
      {ItemId::NeutroniumHarvester,
       "Neutronium Bio-Harvester",
       ItemCategory::Harvester,
       6250,
       0,
       70,
       {0, 0, 0, 0, 30}},
      {ItemId::ChronoHarvester,
       "Chrono Stasis-Harvester",
       ItemCategory::Harvester,
       20000,
       0,
       85,
       {0, 0, 0, 0, 38}},

      // Tools - Mining Drills
      {ItemId::ScrapDrill,
       "Scrap Rotary Drill",
       ItemCategory::Drill,
       10,
       0,
       1,
       {0, 0, 0, 0, 0}},
      {ItemId::TitaniumDrill,
       "Titanium Impact Drill",
       ItemCategory::Drill,
       50,
       0,
       10,
       {0, 0, 0, 0, 6}},
      {ItemId::DurasteelDrill,
       "Durasteel Sonic Drill",
       ItemCategory::Drill,
       180,
       0,
       25,
       {0, 0, 0, 0, 12}},
      {ItemId::CobaltDrill,
       "Cobalt Laser Bore",
       ItemCategory::Drill,
       625,
       0,
       40,
       {0, 0, 0, 0, 18}},
      {ItemId::TungstenDrill,
       "Tungsten Plasma Bore",
       ItemCategory::Drill,
       2000,
       0,
       55,
       {0, 0, 0, 0, 24}},
      {ItemId::NeutroniumDrill,
       "Neutronium Quantum Drill",
       ItemCategory::Drill,
       6250,
       0,
       70,
       {0, 0, 0, 0, 30}},
      {ItemId::ChronoDrill,
       "Chrono Singularity Bore",
       ItemCategory::Drill,
       20000,
       0,
       85,
       {0, 0, 0, 0, 38}},

      // Tools - Synth-Reactors
      {ItemId::BasicReactor,
       "Basic Micro-Reactor",
       ItemCategory::Reactor,
       10,
       0,
       1,
       {0, 0, 0, 0, 0}},
      {ItemId::PlasteelReactor,
       "Plasteel Thermal Unit",
       ItemCategory::Reactor,
       60,
       0,
       10,
       {0, 0, 0, 0, 5}},
      {ItemId::NanotubeReactor,
       "Nanotube Induction Core",
       ItemCategory::Reactor,
       225,
       0,
       25,
       {0, 0, 0, 0, 10}},
      {ItemId::PositronicReactor,
       "Positronic Reactor",
       ItemCategory::Reactor,
       750,
       0,
       45,
       {0, 0, 0, 0, 15}},
      {ItemId::PlasmaReactor,
       "Plasma Fusion Furnace",
       ItemCategory::Reactor,
       2500,
       0,
       60,
       {0, 0, 0, 0, 20}},
      {ItemId::QuantumReactor,
       "Quantum Synth-Core",
       ItemCategory::Reactor,
       7500,
       0,
       75,
       {0, 0, 0, 0, 26}},
      {ItemId::MainframeReactor,
       "AI Mainframe Reactor",
       ItemCategory::Reactor,
       23750,
       0,
       90,
       {0, 0, 0, 0, 34}},

      // Cyberware - Auto-Stim Injectors
      {ItemId::AutoStimMk1,
       "Auto-Stim — Mk I",
       ItemCategory::AutoStim,
       375,
       0,
       1,
       {0, 0, 0, 0, 25}},
      {ItemId::AutoStimMk2,
       "Auto-Stim — Mk II",
       ItemCategory::AutoStim,
       3000,
       0,
       1,
       {0, 0, 0, 0, 40}},
      {ItemId::AutoStimMk3,
       "Auto-Stim — Mk III",
       ItemCategory::AutoStim,
       12500,
       0,
       1,
       {0, 0, 0, 0, 55}},

      // Enemy Salvage
      {ItemId::ServoParts,
       "Servo Parts",
       ItemCategory::CyberLoot,
       8,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::HeavyChassis,
       "Heavy Mech Chassis",
       ItemCategory::CyberLoot,
       30,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::ApexCyberCore,
       "Apex Cyber-Core",
       ItemCategory::CyberLoot,
       180,
       0,
       1,
       {0, 0, 0, 0}},
      {ItemId::Microchip, "Microchip", ItemCategory::CyberLoot, 3, 0, 1, {0, 0, 0, 0}},
      {ItemId::SynthWeaveHide,
       "Synth-Weave Hide",
       ItemCategory::CyberLoot,
       16,
       0,
       1,
       {0, 0, 0, 0}},
  })};
  size_t idx = static_cast<size_t>(id);
  if (idx >= item_info.size()) {
    return item_info[0];
  }
  return item_info[idx];
}


std::string item_category_name(ItemCategory cat) {
  switch (cat) {
    case ItemCategory::Scrap:
      return "Scrap";
    case ItemCategory::RawMaterial:
      return "Raw Material";
    case ItemCategory::RawBiota:
      return "Raw Biota";
    case ItemCategory::Crop:
      return "Crop/Ingr";
    case ItemCategory::StimFood:
      return "Stim/Ration";
    case ItemCategory::ToxicWaste:
      return "Slag";
    case ItemCategory::RawOre:
      return "Ore";
    case ItemCategory::Alloy:
      return "Alloy";
    case ItemCategory::DataCrystal:
      return "Crystal";
    case ItemCategory::Weapon:
      return "Weapon";
    case ItemCategory::Head:
      return "Head";
    case ItemCategory::Armor:
      return "Armor";
    case ItemCategory::Shield:
      return "Shield";
    case ItemCategory::Cutter:
      return "Cutter";
    case ItemCategory::Harvester:
      return "Harvester";
    case ItemCategory::Drill:
      return "Drill";
    case ItemCategory::Reactor:
      return "Reactor";
    case ItemCategory::AutoStim:
      return "Auto-Stim";
    case ItemCategory::CyberLoot:
      return "Salvage";
  }
  return "Item";
}


std::string item_equip_summary(ItemId id) {
  if (!is_valid_item(id)) return "Empty";
  const auto& info = get_item_info(id);
  switch (info.category) {
    case ItemCategory::Cutter:
    case ItemCategory::Harvester:
    case ItemCategory::Drill:
      return std::format("{} (-{}% Cycle)", info.name, info.bonus.speed_bonus_pct);
    case ItemCategory::Reactor:
      return std::format("{} (-{}% Cycle, +{}% XP)", info.name,
                         info.bonus.speed_bonus_pct, info.bonus.speed_bonus_pct);
    case ItemCategory::AutoStim:
      return std::format("{} (Auto-Stim <= {}% HP)", info.name,
                         info.bonus.speed_bonus_pct);
    default:
      return std::format("{} (+{}Atk, +{}Str, +{}Def, {}%DR)", info.name,
                         info.bonus.attack, info.bonus.strength, info.bonus.defence,
                         info.bonus.damage_reduction);
  }
}

std::string item_name(ItemId id) {
  return get_item_info(id).name;
}

