#include "monsters.hpp"

#include <array>
#include <cstddef>
#include <format>

std::string zone_name(ZoneId zone) {
  switch (zone) {
#define X(id, name) \
  case ZoneId::id:  \
    return name;
    RV_ZONE_ID_LIST(X)
#undef X
  }
  return "Unknown";
}

std::span<const ZoneId> all_zone_ids() noexcept {
  static constexpr std::array ids{std::to_array<ZoneId>({
#define X(id, name) ZoneId::id,
      RV_ZONE_ID_LIST(X)
#undef X
  })};
  return ids;
}

std::string monster_name(MonsterId monster) {
  switch (monster) {
#define X(id, name)   \
  case MonsterId::id: \
    return name;
    RV_MONSTER_ID_LIST(X)
#undef X
  }
  return "Unknown";
}

std::span<const MonsterId> all_monster_ids() noexcept {
  static constexpr std::array ids{std::to_array<MonsterId>({
#define X(id, name) MonsterId::id,
      RV_MONSTER_ID_LIST(X)
#undef X
  })};
  return ids;
}

const MonsterInfo& get_monster_info(MonsterId id) {
  static const std::array monster_info{std::to_array<MonsterInfo>({
      // StrayServoDrone: Neon Slums — unconnected (0 INT)
      {MonsterId::StrayServoDrone,
       ZoneId::NeonSlums,
       1,
       30,
       0,
       2600,
       6,
       0,
       0,
       15,
       10,
       20,
       3,
       10,
       1,
       false,
       {{{ItemId::Microchip, 90, 2, 6},
         {ItemId::ScrapCpu, 45, 1, 2},
         {ItemId::ScrapRam, 45, 1, 2},
         {ItemId::ScrapCutter, 12, 1, 1}}}},
      // BioVatHound: Neon Slums — organic, unconnected (0 INT)
      {MonsterId::BioVatHound,
       ZoneId::NeonSlums,
       4,
       65,
       0,
       2800,
       12,
       0,
       0,
       25,
       18,
       42,
       8,
       22,
       1,
       false,
       {{{ItemId::SynthWeaveHide, 85, 1, 2},
         {ItemId::SynthProteinBar, 70, 1, 2},
         {ItemId::ServoParts, 100, 1, 1},
         {ItemId::TitaniumHarvester, 10, 1, 1}}}},
      // SlumDataTerminal: Metaverse Grid — pure Terminal (0 HP, 60 INT)
      {MonsterId::SlumDataTerminal,
       ZoneId::MetaverseGrid,
       5,
       0,
       60,
       2400,
       0,
       9,
       3,
       28,
       20,
       52,
       12,
       30,
       1,
       false,
       {{{ItemId::ScrapCpu, 85, 1, 3},
         {ItemId::ScrapRam, 85, 1, 3},
         {ItemId::SpikeIceMk1, 60, 3, 6},
         {ItemId::ParityPatch, 40, 1, 2}}}},
      // StreetScavenger: Neon Slums — unconnected (0 INT)
      {MonsterId::StreetScavenger,
       ZoneId::NeonSlums,
       9,
       110,
       0,
       2600,
       20,
       0,
       0,
       40,
       32,
       72,
       18,
       45,
       1,
       false,
       {{{ItemId::PlasteelShards, 50, 2, 5},
         {ItemId::SynthCarpPack, 40, 1, 2},
         {ItemId::ServoParts, 100, 1, 1},
         {ItemId::TitaniumCutter, 10, 1, 1}}}},
      // ChromeGangPunk: Back-Alley Sector — connected cyber-punk (160 HP, 90 INT)
      {MonsterId::ChromeGangPunk,
       ZoneId::BackAlleySector,
       14,
       160,
       90,
       2500,
       28,
       10,
       2,
       55,
       45,
       105,
       28,
       70,
       1,
       false,
       {{{ItemId::ScrapBlade, 15, 1, 1},
         {ItemId::TitaniumOre, 45, 2, 4},
         {ItemId::SpikeIceMk1, 50, 2, 5},
         {ItemId::TitaniumDrill, 10, 1, 1}}}},
      // RiotEnforcerBot: Industrial Sector — networked bot (280 HP, 180 INT)
      {MonsterId::RiotEnforcerBot,
       ZoneId::IndustrialSector,
       24,
       280,
       180,
       3000,
       45,
       18,
       3,
       85,
       72,
       185,
       55,
       130,
       10,
       false,
       {{{ItemId::HeavyChassis, 100, 1, 2},
         {ItemId::DurasteelBlade, 12, 1, 1},
         {ItemId::PositronicCpu, 35, 1, 2},
         {ItemId::DurasteelCutter, 10, 1, 1}}}},
      // CorpSubroutineAi: Metaverse Grid — pure AI (0 HP, 260 INT)
      {MonsterId::CorpSubroutineAi,
       ZoneId::MetaverseGrid,
       28,
       0,
       260,
       2500,
       0,
       32,
       5,
       100,
       85,
       230,
       75,
       175,
       15,
       false,
       {{{ItemId::PositronicCpu, 75, 1, 2},
         {ItemId::OpticRam, 75, 1, 2},
         {ItemId::BreachIceMk2, 55, 4, 8},
         {ItemId::KernelHotfix, 40, 1, 2}}}},
      // ChemMutantBrute: Industrial Sector — organic mutant, unconnected (450 HP, 0 INT)
      {MonsterId::ChemMutantBrute,
       ZoneId::IndustrialSector,
       36,
       450,
       0,
       3000,
       68,
       0,
       0,
       120,
       105,
       295,
       95,
       220,
       20,
       false,
       {{{ItemId::HeavyChassis, 100, 1, 2},
         {ItemId::CobaltOre, 45, 2, 5},
         {ItemId::CyberLobsterMeal, 35, 2, 4},
         {ItemId::DurasteelHarvester, 10, 1, 1}}}},
      // CryoSecMech: Industrial Sector — connected mech (650 HP, 420 INT)
      {MonsterId::CryoSecMech,
       ZoneId::IndustrialSector,
       48,
       650,
       420,
       2900,
       92,
       42,
       4,
       165,
       145,
       430,
       150,
       340,
       30,
       false,
       {{{ItemId::HeavyChassis, 100, 2, 3},
         {ItemId::CobaltExoSuit, 10, 1, 1},
         {ItemId::SapphireCortex, 25, 1, 2},
         {ItemId::CobaltDrill, 8, 1, 1}}}},
      // BlackwallDaemon: Metaverse Grid — pure AI Daemon (0 HP, 750 INT)
      {MonsterId::BlackwallDaemon,
       ZoneId::MetaverseGrid,
       58,
       0,
       750,
       2500,
       0,
       78,
       7,
       210,
       190,
       560,
       220,
       500,
       38,
       false,
       {{{ItemId::QuantumCpu, 70, 1, 2},
         {ItemId::CryoRam, 70, 1, 2},
         {ItemId::KrakenIceMk4, 50, 4, 8},
         {ItemId::NeuralFirewall, 12, 1, 1}}}},
      // CorpShadowOp: Megacorp Plaza — connected operative (880 HP, 600 INT)
      {MonsterId::CorpShadowOp,
       ZoneId::MegacorpPlaza,
       60,
       880,
       600,
       2700,
       125,
       60,
       5,
       215,
       195,
       580,
       230,
       520,
       40,
       false,
       {{{ItemId::TungstenBlade, 12, 1, 1},
         {ItemId::TungstenOre, 45, 2, 5},
         {ItemId::PlasmaRayInfusion, 40, 2, 4},
         {ItemId::PositronicReactor, 8, 1, 1}}}},
      // CobaltCyberNinja: Megacorp Plaza — connected cyber-ninja (1150 HP, 800 INT)
      {MonsterId::CobaltCyberNinja,
       ZoneId::MegacorpPlaza,
       74,
       1150,
       800,
       2600,
       160,
       80,
       6,
       270,
       250,
       780,
       350,
       780,
       50,
       false,
       {{{ItemId::TungstenExoSuit, 10, 1, 1},
         {ItemId::RubyLaserCore, 30, 1, 2},
         {ItemId::ApexSharkBooster, 35, 2, 4},
         {ItemId::TungstenCutter, 8, 1, 1}}}},
      // NeutroniumCyborg: Megacorp Plaza — connected cyborg (1500 HP, 1100 INT)
      {MonsterId::NeutroniumCyborg,
       ZoneId::MegacorpPlaza,
       88,
       1500,
       1100,
       2500,
       205,
       110,
       7,
       340,
       320,
       1050,
       550,
       1200,
       65,
       false,
       {{{ItemId::NeutroniumBlade, 10, 1, 1},
         {ItemId::NeutroniumExoSuit, 8, 1, 1},
         {ItemId::EmeraldCryptokey, 30, 1, 2},
         {ItemId::NeutroniumDrill, 7, 1, 1}}}},
      // ArchonNetAi: Metaverse Grid — pure Overmind AI (0 HP, 1900 INT)
      {MonsterId::ArchonNetAi,
       ZoneId::MetaverseGrid,
       95,
       0,
       1900,
       2400,
       0,
       165,
       10,
       390,
       370,
       1350,
       750,
       1700,
       70,
       false,
       {{{ItemId::NeuralCpu, 75, 1, 3},
         {ItemId::QuantumRam, 75, 1, 3},
         {ItemId::SingularityIceMk6, 50, 5, 10},
         {ItemId::QuantumFirewall, 10, 1, 1}}}},
      // ApexCyberWyrm: Orbital Spire — connected wyrm (2150 HP, 1600 INT)
      {MonsterId::ApexCyberWyrm,
       ZoneId::OrbitalSpire,
       110,
       2150,
       1600,
       2600,
       270,
       150,
       8,
       430,
       410,
       1500,
       900,
       2000,
       75,
       false,
       {{{ItemId::ApexCyberCore, 100, 1, 2},
         {ItemId::ChronoBlade, 15, 1, 1},
         {ItemId::QuantumOre, 30, 1, 3},
         {ItemId::ChronoHarvester, 6, 1, 1}}}},
      // Nexus9: Mainframe Core [BOSS] — hybrid Overmind (3500 HP, 3000 INT)
      {MonsterId::Nexus9,
       ZoneId::MainframeCore,
       150,
       3500,
       3000,
       2400,
       360,
       220,
       12,
       550,
       520,
       3000,
       2500,
       5500,
       85,
       true,
       {{{ItemId::QuantumBlade, 15, 1, 1},
         {ItemId::QuantumExoSuit, 12, 1, 1},
         {ItemId::SingularityFirewall, 10, 1, 1},
         {ItemId::MainframeReactor, 5, 1, 1}}}},
  })};
  size_t idx = static_cast<size_t>(id);
  if (idx < monster_info.size()) {
    return monster_info[idx];
  }
  return monster_info[0];
}

std::string monster_summary(MonsterId id) {
  const auto& mon = get_monster_info(id);
  return std::format("{} (Lv {}, {} HP / {} INT, MaxHit {}/{}, {})", monster_name(id),
                     mon.combat_level, mon.max_hp, mon.max_integrity, mon.max_hit,
                     mon.ice_max_hit, zone_name(mon.zone));
}
